services:
    php:
        container_name: php
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        restart: always
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - internal

    db:
        container_name: db
        image: mysql:8.1
        restart: always
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=secret
        ports:
            - "3309:3306"
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - internal

volumes:
    db-volume:

networks:
    internal:
        driver: bridge
